[build]
  functions = "functions"
  base = "functions/gen-opengraph-label"
  publish = "build"
  command = "npm i --legacy-peer-deps && npm run build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"